name: Generate Snake Animation

on:
  schedule:
    # Berjalan setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch:

# ==========================================================
#  INI PENAMBAHANNYA: Memberi izin pada workflow
#  untuk menulis (push) hasil gambarnya ke repo
# ==========================================================
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: reyibra
          # Daftar output yang akan dibuat, 'svg' saja cukup
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # Direktori yang akan di-deploy
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
